### ISSUE TITLE
Any plans to support cross compiling on a Linux host machine?

### ISSUE THREAD

**Issue by isso** [AbhraneelBera/wiringBone#10]
I was wondering, are there any plans to support cross compiling on a Linux host machine?

I would like to be able to compile programs on my machine then send the binaries to BBB for exection.

**Comment by Rahul5214** [comment]
There is lot of content on the web to help you out with this.
You may try [this](https://www.acmesystems.it/arm9_toolchain) and [this](http://exploringbeaglebone.com/chapter7/)

**Comment by isso** [comment]
Got it! thanks. I thought the PRU dependencies would introduce problems when cross-compiling?

I haven't read through the code, but I guess the library loads the PRUs of the BB on runtime using prebuilt binaries, am I correct?
